
<Body>:
    id: err
    orientation: 'vertical'
    size_hint: 0.9, 0.9
    pos_hint: {'center_x':0.5,'center_y':0.5}
    


    Image:
        id: image
        source: 'lupa.jpg'
        
    Label:
        text: 'Bear Search'
        font_size: 70
        bold: False
        color: 0,0,0,1
        
    FileChooserListView:
        id: filechooser
        dirselect: True
        on_selection: err.selected(filechooser.selection,*args)

        
    GridLayout:
        cols: 2
        
        MDRaisedButton:
            text: 'Search'
            on_release:
                root.search()
            
    AnchorLayout:
        anchor_x: 'center'
        anchor_y: 'bottom'
        
        MDRaisedButton:
            text: 'Authors'
            on_release:
                root.authors()



            
            
        